// Generated by CoffeeScript 1.7.1
(function() {
  var App, MotionAnalysis, QueryString,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  MotionAnalysis = (function() {
    MotionAnalysis.prototype.rotation = null;

    MotionAnalysis.prototype.acceleration = null;

    MotionAnalysis.prototype.gravity = null;

    MotionAnalysis.prototype.invertX = 1;

    MotionAnalysis.prototype.invertY = 1;

    MotionAnalysis.prototype.invertZ = 1;

    MotionAnalysis.prototype.addY = 0;

    MotionAnalysis.prototype.status = null;

    function MotionAnalysis() {
      this.onGyroscopeData = __bind(this.onGyroscopeData, this);
      this.onAccelerometerData = __bind(this.onAccelerometerData, this);
      this.onCompassNeedsCalibration = __bind(this.onCompassNeedsCalibration, this);
      this.rotation = {
        x: 0,
        y: 0,
        z: 0
      };
      this.acceleration = {
        x: 0,
        y: 0,
        z: 0
      };
      this.gravity = {
        x: 0,
        y: 0,
        z: 0
      };
      this.invertY = -1;
      this.addY = -360;
      if (window.DeviceOrientationEvent) {
        window.addEventListener('deviceorientation', this.onGyroscopeData, true);
      }
      if (window.DeviceMotionEvent) {
        window.addEventListener('devicemotion', this.onAccelerometerData, true);
      }
      window.addEventListener('compassneedscalibration ', this.onCompassNeedsCalibration, true);
      this;
    }

    MotionAnalysis.prototype.onCompassNeedsCalibration = function(e) {
      console.log("COMPASS NEEDS CALIBRATION");
      return this;
    };

    MotionAnalysis.prototype.onAccelerometerData = function(e) {
      this.gravity.x = -e.accelerationIncludingGravity.x * this.invertX;
      this.gravity.y = e.accelerationIncludingGravity.z * this.invertY;
      this.gravity.z = -e.accelerationIncludingGravity.y * this.invertZ;
      this.acceleration.x = e.rotationRate.alpha * this.invertX;
      this.acceleration.y = e.rotationRate.gamma * this.invertY;
      this.acceleration.z = e.rotationRate.beta * this.invertZ;
      return this;
    };

    MotionAnalysis.prototype.onGyroscopeData = function(e) {
      this.rotation.x = -e.beta * this.invertX;
      this.rotation.y = (e.alpha + this.addY) * this.invertY;
      this.rotation.z = -e.gamma * this.invertZ;
      this.rotation.absolute = e.absolute != null ? e.absolute : false;
      return this;
    };

    MotionAnalysis.prototype.wrapAngle = function(value) {
      value = value % 360;
      if (value <= 180) {
        return value;
      } else {
        return value - 360;
      }
    };

    return MotionAnalysis;

  })();

  QueryString = (function() {
    function QueryString() {}

    QueryString.get = function(name) {
      var regex, regexS, results;
      if (name) {
        name = name.replace(/[\[]/, "\\\[").replace(/[\]]/, "\\\]");
        regexS = "[\\?&]" + name + "=([^&#]*)";
        regex = new RegExp(regexS);
        results = regex.exec(window.location.search);
        if (results === null) {
          return "";
        } else {
          return decodeURIComponent(results[1].replace(/\+/g, " "));
        }
      } else {
        return "";
      }
    };

    return QueryString;

  })();

  App = (function() {
    App.prototype.CONTAINER_X = 200;

    App.prototype.SCREEN_WIDTH = window.innerWidth - App.CONTAINER_X;

    App.prototype.SCREEN_HEIGHT = window.innerHeight;

    App.prototype.FLOOR = -50;

    App.prototype.TRANSITION_DURATION = 0.5;

    App.prototype.PAGE_SCALE_MULTIPLIER = 0.1;

    App.prototype.SCENE_SCALE_MULTIPLIER = 100;

    App.prototype.CSS3D_SCALE_MULTIPLIER = 1;

    App.prototype.container = null;

    App.prototype.camera = null;

    App.prototype.scene = null;

    App.prototype.css3DScene = null;

    App.prototype.renderer = null;

    App.prototype.css3dRenderer = null;

    App.prototype.isWebGLCapable = false;

    App.prototype.isCSS3DCapable = false;

    App.prototype.isCanvasCapable = false;

    App.prototype.isIE11 = false;

    App.prototype.mouseX = 0;

    App.prototype.mouseY = 0;

    App.prototype.pickMouseX = -90000;

    App.prototype.pickMouseY = -90000;

    App.prototype.windowHalfX = App.SCREEN_WIDTH / 2;

    App.prototype.windowHalfY = App.SCREEN_HEIGHT / 2;

    App.prototype.projector = null;

    App.prototype.raycaster = null;

    App.prototype.overObject = null;

    App.prototype.excludeFromPicking = ["scene_baked_pPlane1"];

    App.prototype.initialObjectsProperties = {};

    App.prototype.clickedObject = null;

    App.prototype.clickedObjectWPosition = null;

    App.prototype.clickedObjectWRotation = null;

    App.prototype.clickedObjectWScale = null;

    App.prototype.isFocused = false;

    App.prototype.doRender = true;

    App.prototype.pageLanguage = window.PAGE_LANG;

    App.prototype.pagePermalink = window.PAGE_PERMALINK;

    App.prototype.pageDepth = window.PAGE_DEPTH;

    App.prototype.pageBase = window.PAGE_BASE;

    App.prototype.pageId = "";

    App.prototype.config = [];

    App.prototype.allLanguagesConfig = [];

    App.prototype.thisPageConfig = null;

    App.prototype.page3DObjects = {};

    App.prototype.doPicking = true;

    App.prototype.currentHistoryState = {};

    App.prototype.cameraLookAt = new THREE.Vector3(-50, -300, 0);

    App.prototype.htmlMain = null;

    App.prototype.delayID = -1;

    App.prototype.minCameraX = -250;

    App.prototype.maxCameraX = 250;

    App.prototype.minCameraY = -50;

    App.prototype.maxCameraY = 300;

    App.prototype.unfocusingTween = null;

    App.prototype.motionAnalysis = null;

    App.prototype.lockedOnDeviceMotion = false;

    App.prototype.deviceMotionChangeTimes = 0;

    App.prototype.prevMotionAnalysis = {
      x: 0,
      y: 0,
      z: 0
    };

    function App() {
      this.hideLoading = __bind(this.hideLoading, this);
      this.showLoading = __bind(this.showLoading, this);
      this.getRelativeLink = __bind(this.getRelativeLink, this);
      this.getUpDirs = __bind(this.getUpDirs, this);
      this.handle3DPlaneMouseInteraction = __bind(this.handle3DPlaneMouseInteraction, this);
      this.calcPicking = __bind(this.calcPicking, this);
      this.render = __bind(this.render, this);
      this.animate = __bind(this.animate, this);
      this.onMouseMove = __bind(this.onMouseMove, this);
      this.onWindowResize = __bind(this.onWindowResize, this);
      this.getFocusedPagePosition = __bind(this.getFocusedPagePosition, this);
      this.syncCss3dPlaneRotation = __bind(this.syncCss3dPlaneRotation, this);
      this.syncCss3dPlanePosition = __bind(this.syncCss3dPlanePosition, this);
      this.syncCss3dPlaneScale = __bind(this.syncCss3dPlaneScale, this);
      this.unfocus = __bind(this.unfocus, this);
      this.focus = __bind(this.focus, this);
      this.replaceThreeJsMaterial = __bind(this.replaceThreeJsMaterial, this);
      this.sceneLoadCallback = __bind(this.sceneLoadCallback, this);
      this.setupCSS3DPage = __bind(this.setupCSS3DPage, this);
      this.onTouchEnd = __bind(this.onTouchEnd, this);
      this.onTouchMove = __bind(this.onTouchMove, this);
      this.onTouchStart = __bind(this.onTouchStart, this);
      this.onConfigError = __bind(this.onConfigError, this);
      this.handlePushState = __bind(this.handlePushState, this);
      this.on3DSceneMouseClick = __bind(this.on3DSceneMouseClick, this);
      this.findMenuItemByPermalink = __bind(this.findMenuItemByPermalink, this);
      this.on3DPlaneMouseOut = __bind(this.on3DPlaneMouseOut, this);
      this.on3DPlaneMouseOver = __bind(this.on3DPlaneMouseOver, this);
      this.onCloseClick = __bind(this.onCloseClick, this);
      this.onMenuLinkClick = __bind(this.onMenuLinkClick, this);
      this.onMenuLinkOut = __bind(this.onMenuLinkOut, this);
      this.onMenuLinkOver = __bind(this.onMenuLinkOver, this);
      this.scrollMenuToItem = __bind(this.scrollMenuToItem, this);
      this.onPopStateChange = __bind(this.onPopStateChange, this);
      this.onConfigLoaded = __bind(this.onConfigLoaded, this);
      this.isIE11 = !!window.MSInputMethodContext;
      this.isCSS3DCapable = Modernizr.csstransforms3d && !this.isIE11;
      this.isWebGLCapable = this.checkWebGL() && Modernizr.webgl;
      this.isPushStateCapable = Modernizr.history;
      if (this.isCSS3DCapable && this.isPushStateCapable && (this.isCanvasCapable || this.isWebGLCapable)) {
        this.htmlMain = $("main");
        ga('send', 'event', 'webgl-test', 'passed');
        $("body").css("overflow-y", "hidden");
        $("html").css("overflow-y", "hidden");
        TweenMax.to(this.htmlMain, 1, {
          css: {
            opacity: 0
          },
          onComplete: (function(_this) {
            return function(thisPage) {
              _this.showLoading();
              TweenMax.to(_this.htmlMain, 0, {
                css: {
                  opacity: 1
                }
              });
              _this.htmlMain.remove();
              $.ajax(_this.pageBase + "config.json", {
                success: _this.onConfigLoaded,
                error: _this.onConfigError
              });
              _this.init();
              return _this.animate();
            };
          })(this)
        });
      } else {
        ga('send', 'event', 'webgl-test', 'failed');
      }
      null;
    }

    App.prototype.init = function() {
      this.container = $('.javascriptContent');
      this.CONTAINER_X = this.container.position().left;
      this.SCREEN_WIDTH = window.innerWidth - this.CONTAINER_X;
      this.SCREEN_HEIGHT = window.innerHeight;
      this.windowHalfX = this.SCREEN_WIDTH / 2;
      this.windowHalfY = this.SCREEN_HEIGHT / 2;
      this.motionAnalysis = new MotionAnalysis();
      this.camera = new THREE.PerspectiveCamera(75, this.SCREEN_WIDTH / this.SCREEN_HEIGHT, 1, 10000);
      this.camera.position.z = 300;
      this.scene = new THREE.Scene();
      this.css3DScene = new THREE.Scene();
      this.css3DScene.scale.set(this.CSS3D_SCALE_MULTIPLIER, this.CSS3D_SCALE_MULTIPLIER, this.CSS3D_SCALE_MULTIPLIER);
      this.css3DScene.updateMatrix();
      if (this.isWebGLCapable) {
        this.renderer = new THREE.WebGLRenderer({
          antialias: true
        });
        this.renderer.gammeInput = true;
        this.renderer.gammeOutput = true;
      } else if (this.isCanvasCapable) {
        this.renderer = new THREE.CanvasRenderer;
      }
      this.renderer.setClearColor(0xffffff, 1);
      this.renderer.setSize(this.SCREEN_WIDTH, this.SCREEN_HEIGHT);
      this.renderer.domElement.style.position = "relative";
      $(this.renderer.domElement).addClass("threejs-container");
      this.container.append(this.renderer.domElement);
      this.css3dRenderer = new THREE.CSS3DRenderer();
      this.css3dRenderer.setClearColor(0xffffff);
      this.css3dRenderer.setSize(this.SCREEN_WIDTH, this.SCREEN_HEIGHT);
      this.css3dRenderer.domElement.style.position = "absolute";
      this.css3dRenderer.domElement.style.top = "0";
      this.css3dRenderer.domElement.style.left = "0";
      $(this.css3dRenderer.domElement).addClass("css3d-container");
      this.container.append(this.css3dRenderer.domElement);
      this.projector = new THREE.Projector();
      this.raycaster = new THREE.Raycaster();
      $(window).bind('resize', this.onWindowResize);
      this.container.bind('mousemove touchmove touchstart', this.onMouseMove);
      this.container.bind('click touchend', this.on3DSceneMouseClick);
      this.container.bind("transitionend webkitTransitionEnd oTransitionEnd otransitionend MSTransitionEnd", this.onWindowResize);
      $(".projectsMenu").find("a").mouseover(this.onMenuLinkOver);
      $(".projectsMenu").find("a").mouseout(this.onMenuLinkOut);
      $(".projectsMenu").find("a").click(this.onMenuLinkClick);
      $(".menu").find("a").mouseover((function(_this) {
        return function() {
          return _this.doPicking = false;
        };
      })(this));
      $(".menu").find("a").mouseout((function(_this) {
        return function() {
          return _this.doPicking = true;
        };
      })(this));
      $(".close-page").click(this.onCloseClick);
      $(window).bind("popstate", this.onPopStateChange);
      this.onWindowResize();
      TweenMax.to($(".threejs-container"), 0, {
        css: {
          opacity: 0
        }
      });
      TweenMax.to($(".css3d-container"), 0, {
        css: {
          opacity: 0
        }
      });
      if ((this.pagePermalink != null) && this.pagePermalink !== "") {
        this.currentHistoryState = "/" + this.pageLanguage + "/" + this.pagePermalink + "/";
      } else {
        this.currentHistoryState = "/" + this.pageLanguage + "/";
      }
      return null;
    };

    App.prototype.onConfigLoaded = function(data, textStatus, jqXHR) {
      var loader;
      this.allLanguagesConfig = data;
      this.config = data[this.pageLanguage];
      if (this.config == null) {
        throw "Cannot find config for this language";
      }
      loader = new THREE.SceneLoader();
      if (this.isWebGLCapable) {
        loader.load(this.pageBase + "maya/data/scene.json", this.sceneLoadCallback);
      } else {
        loader.load(this.pageBase + "maya/data/scene_canvas.json", this.sceneLoadCallback);
      }
      return null;
    };

    App.prototype.onPopStateChange = function(event) {
      var languageConfig, languageLink, languageLinks, newPath, obj3D, page, selectedMenuItem, _i, _j, _k, _len, _len1, _len2, _ref;
      if (event.originalEvent.state == null) {
        return;
      }
      newPath = event.originalEvent.state.path;
      _ref = this.config;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        page = _ref[_i];
        if (page.link === newPath) {
          this.pageId = page.meta.id;
          this.thisPageConfig = page;
          break;
        }
      }
      this.pageLanguage = this.thisPageConfig.lang;
      this.pagePermalink = this.thisPageConfig.meta.permalink;
      this.pageDepth = this.thisPageConfig.depth;
      this.pageBase = this.thisPageConfig.base;
      document.title = "Daniele Pelagatti - " + this.thisPageConfig.meta.title;
      obj3D = this.page3DObjects[newPath];
      if ((this.unfocusingTween != null) && !this.unfocusingTween._active) {
        this.unfocusingTween = null;
      }
      if (this.unfocusingTween != null) {
        this.unfocusingTween.vars.onCompleteParams[1] = (function(_this) {
          return function() {
            _this.clickedObject = _this.overObject = obj3D;
            _this.unfocusingTween = null;
            return _this.focus();
          };
        })(this);
      } else if (this.isFocused) {
        if (newPath !== this.currentHistoryState) {
          this.unfocus((function(_this) {
            return function() {
              _this.clickedObject = _this.overObject = obj3D;
              return _this.focus();
            };
          })(this));
        }
      } else {
        this.overObject = this.clickedObject = obj3D;
        this.focus();
      }
      if (newPath !== this.currentHistoryState) {
        languageLinks = $(".languagesMenu").find("a");
        for (_j = 0, _len1 = languageLinks.length; _j < _len1; _j++) {
          languageLink = languageLinks[_j];
          languageConfig = this.allLanguagesConfig[languageLink.id];
          for (_k = 0, _len2 = languageConfig.length; _k < _len2; _k++) {
            page = languageConfig[_k];
            if (page.meta.id === this.pageId) {
              $(languageLink).attr("href", this.getRelativeLink(page.link));
            }
          }
        }
        selectedMenuItem = this.findMenuItemByPermalink(newPath, (function(_this) {
          return function(item) {
            return item.removeClass("selected");
          };
        })(this), (function(_this) {
          return function(item) {
            item.attr("href", _this.pageBase + _this.getRelativeLink(item.attr("permalink")).substr(1));
            return item.parent().removeClass("hover");
          };
        })(this));
        if (selectedMenuItem != null) {
          selectedMenuItem.addClass("selected");
          this.scrollMenuToItem(selectedMenuItem);
        }
        ga('send', 'pageview', this.thisPageConfig.link);
        this.currentHistoryState = newPath;
      }
      return null;
    };

    App.prototype.scrollMenuToItem = function(item) {
      var scrollTarget, scrollToY, scroller, targetPosition;
      scrollTarget = $(".menu");
      targetPosition = item.position();
      scroller = scrollTarget.scrollTop();
      scrollToY = (targetPosition.top + scroller) - (this.SCREEN_HEIGHT / 2);
      TweenMax.to(scrollTarget[0], 0.5, {
        scrollTo: {
          y: scrollToY
        },
        ease: Power2.easeOut
      });
      return null;
    };

    App.prototype.onMenuLinkOver = function(event) {
      var obj3D;
      if (!this.isFocused) {
        obj3D = this.page3DObjects[$(event.currentTarget).attr("permalink")];
        this.handle3DPlaneMouseInteraction(obj3D, "menu");
      }
      return null;
    };

    App.prototype.onMenuLinkOut = function(event) {
      return null;
    };

    App.prototype.onMenuLinkClick = function(event) {
      event.originalEvent.preventDefault();
      this.on3DPlaneMouseOut(this.overObject);
      this.overObject = null;
      this.handlePushState($(event.currentTarget).attr("permalink"));
      return null;
    };

    App.prototype.onCloseClick = function() {
      ga('send', 'event', 'close-page-button', 'click');
      this.unfocus();
      return null;
    };

    App.prototype.on3DPlaneMouseOver = function(plane, source) {
      var menuItem;
      if (!this.isFocused) {
        if (this.isWebGLCapable) {
          TweenMax.to(plane.material.uniforms.color_opacity, 0.5, {
            value: 1
          });
        }
        if (source !== "menu") {
          menuItem = this.findMenuItemByPermalink(plane.page.attr("permalink"), function(item) {
            return item.parent().removeClass("hover");
          });
          menuItem.parent().addClass("hover");
          this.scrollMenuToItem(menuItem);
        }
      }
      return null;
    };

    App.prototype.on3DPlaneMouseOut = function(plane, source) {
      var menuItem;
      if (plane == null) {
        return;
      }
      if (this.isWebGLCapable) {
        TweenMax.to(plane.material.uniforms.color_opacity, 0.5, {
          value: 0
        });
      }
      if (!this.isFocused) {
        menuItem = this.findMenuItemByPermalink(plane.page.attr("permalink"));
        menuItem.parent().removeClass("hover");
      }
      return null;
    };

    App.prototype.findMenuItemByPermalink = function(permalink, executeOnOthers, executeOnAll) {
      var menuItem, projectLink, projectsLinks, retValue, _i, _len;
      projectsLinks = $(".projectsMenu").find("a");
      retValue = null;
      for (_i = 0, _len = projectsLinks.length; _i < _len; _i++) {
        menuItem = projectsLinks[_i];
        projectLink = $(menuItem);
        if (projectLink.attr("permalink") === permalink) {
          retValue = projectLink;
        } else {
          if (typeof executeOnOthers === "function") {
            executeOnOthers(projectLink);
          }
        }
        if (typeof executeOnAll === "function") {
          executeOnAll(projectLink);
        }
      }
      return retValue;
    };

    App.prototype.on3DSceneMouseClick = function(event) {
      this.calcPicking();
      if (this.overObject == null) {
        if (!this.isFocused) {
          if (this.overObject) {
            this.clickedObject = this.overObject;
            this.focus();
          }
        } else {
          if (!this.overObject) {
            this.unfocus();
          }
        }
        ga('send', 'event', '3d-empty-space', 'click');
        return;
      }
      ga('send', 'event', '3d-plane:' + this.overObject.link, 'click');
      return this.handlePushState(this.overObject.link);
    };

    App.prototype.handlePushState = function(path) {
      var stateObj;
      stateObj = {
        path: path
      };
      if (path !== this.currentHistoryState) {
        history.pushState(stateObj, "Title", this.pageBase + path.substr(1));
      }
      return this.onPopStateChange({
        originalEvent: {
          state: stateObj
        }
      });
    };

    App.prototype.onConfigError = function(jqXHR, textStatus, errorThrown) {
      throw errorThrown;
    };

    App.prototype.onTouchStart = function(event) {};

    App.prototype.onTouchMove = function(event) {};

    App.prototype.onTouchEnd = function(event) {};

    App.prototype.setupCSS3DPage = function(pageObj, object, link) {
      var cssObj, rot2;
      pageObj.css({
        opacity: 0,
        display: "none"
      });
      cssObj = new THREE.CSS3DObject(pageObj[0]);
      cssObj.rotation.order = "ZYX";
      cssObj.position.set(object.position.x * this.SCENE_SCALE_MULTIPLIER, object.position.y * this.SCENE_SCALE_MULTIPLIER, object.position.z * this.SCENE_SCALE_MULTIPLIER);
      cssObj.quaternion.set(object.quaternion.x, object.quaternion.y, object.quaternion.z, object.quaternion.w);
      rot2 = new THREE.Quaternion();
      rot2.setFromAxisAngle(new THREE.Vector3(1, 0, 0), -Math.PI / 2);
      cssObj.quaternion.multiply(rot2);
      cssObj.scale.set(object.scale.x * this.PAGE_SCALE_MULTIPLIER, object.scale.y * this.PAGE_SCALE_MULTIPLIER, object.scale.z * this.PAGE_SCALE_MULTIPLIER);
      object.page = pageObj;
      object.cssObj = cssObj;
      this.css3DScene.add(cssObj);
      return null;
    };

    App.prototype.sceneLoadCallback = function(result) {
      var objectIndex, thisPage;
      $(".page-container").css({
        display: "none"
      });
      this.colors = paletteGenerator.generate(result.scene.children.length, function(color) {
        var hcl;
        hcl = color.hcl();
        return hcl[0] >= 0 && hcl[0] <= 360 && hcl[1] >= 0 && hcl[1] <= 0.9 && hcl[2] >= 1 && hcl[2] <= 1.5;
      }, false, 50);
      this.colors = paletteGenerator.diffSort(this.colors);
      objectIndex = 0;
      thisPage = null;
      result.scene.traverse((function(_this) {
        return function(object) {
          var container, link;
          object.rotation.order = "ZYX";
          if (object.material != null) {
            if (_this.excludeFromPicking.indexOf(object.name) === -1) {
              _this.initialObjectsProperties[object.name] = {};
              _this.initialObjectsProperties[object.name].position = object.position.clone();
              _this.initialObjectsProperties[object.name].quaternion = object.quaternion.clone();
              _this.initialObjectsProperties[object.name].scale = object.scale.clone();
              if (_this.config[objectIndex] != null) {
                object.config = _this.config[objectIndex];
                _this.page3DObjects[_this.config[objectIndex].link] = object;
                link = object.link = _this.config[objectIndex].link;
                container = $("<div class='object3DContainer' permalink='" + link + "'></div>");
                if (object.config.meta.permalink === _this.pagePermalink || (object.config.meta.permalink === null && _this.pagePermalink === "")) {
                  _this.htmlMain.find("#no-webgl-warning").remove();
                  _this.htmlMain.find(".no-webgl-warning-button").remove();
                  container.append(_this.htmlMain);
                  thisPage = link;
                }
                _this.setupCSS3DPage(container, object, link);
              } else {
                _this.excludeFromPicking.push(object.name);
              }
              objectIndex++;
            }
            if (_this.isWebGLCapable) {
              _this.replaceThreeJsMaterial(object, objectIndex);
              if (object.name !== "scene_baked_pPlane1") {
                object.material.uniforms.fresnelIntensity.value = 1;
              }
            } else {
              object.material = new THREE.MeshBasicMaterial({
                lights: false,
                fog: false,
                shading: THREE.FlatShading,
                map: object.material.map
              });
              object.material.overdraw = true;
            }
            object.material.transparent = true;
            object.material.opacity = 1;
            object.material.side = THREE.DoubleSide;
          }
          if (object.geometry != null) {
            object.geometry.computeFaceNormals();
            object.geometry.computeVertexNormals();
            object.geometry.computeTangents();
            object.geometry.computeBoundingBox();
          }
          return object.updateMatrix();
        };
      })(this));
      this.scene = result.scene;
      this.scene.position.set(0, -450, 0);
      this.css3DScene.position.set(0, -450, 0);
      this.scene.scale.set(this.SCENE_SCALE_MULTIPLIER, this.SCENE_SCALE_MULTIPLIER, this.SCENE_SCALE_MULTIPLIER);
      this.scene.updateMatrix();
      this.css3DScene.updateMatrix();
      this.hideLoading();
      TweenMax.to($(".threejs-container"), 1, {
        css: {
          opacity: 1
        }
      });
      TweenMax.to($(".css3d-container"), 1, {
        css: {
          opacity: 1
        },
        onCompleteParams: [thisPage],
        onCompleteParams: [thisPage],
        onComplete: (function(_this) {
          return function(thisPage) {
            if (thisPage != null) {
              return _this.handlePushState(thisPage);
            }
          };
        })(this)
      });
      return null;
    };

    App.prototype.replaceThreeJsMaterial = function(object, objectIndex) {
      var defines, material, uniforms;
      uniforms = THREE.UniformsUtils.clone(THREE.PlaneShader.uniforms);
      uniforms.color_opacity.value = 0;
      uniforms.opacity.value = 1;
      uniforms.diffuse.value.set(this.colors[objectIndex].rgb[0] / 255, this.colors[objectIndex].rgb[1] / 255, this.colors[objectIndex].rgb[2] / 255);
      uniforms.map.value = object.material.map;
      defines = {};
      defines["USE_MAP"] = "";
      if (this.isIE11) {
        defines["NO_FRESNEL"] = "";
      }
      material = new THREE.ShaderMaterial({
        uniforms: uniforms,
        attributes: {},
        vertexShader: THREE.PlaneShader.vertexShader,
        fragmentShader: THREE.PlaneShader.fragmentShader,
        transparent: true,
        lights: false,
        fog: false,
        shading: THREE.FlatShading,
        defines: defines
      });
      return object.material = material;
    };

    App.prototype.focus = function(callback) {
      var camRot, newPos, pageIsLoaded, rot2;
      this.isFocused = true;
      pageIsLoaded = this.clickedObject.page.find("main").length > 0;
      if (!pageIsLoaded) {
        this.showLoading();
        $.ajax(this.getRelativeLink(this.clickedObject.page.attr("permalink")), {
          success: (function(_this) {
            return function(data, textStatus, jqXHR) {
              var mainArticle;
              mainArticle = $(data).find("main");
              mainArticle.find("#no-webgl-warning").remove();
              mainArticle.find(".no-webgl-warning-button").remove();
              _this.clickedObject.page.append(mainArticle);
              return _this.focus();
            };
          })(this),
          error: (function(_this) {
            return function(jqXHR, textStatus, errorThrown) {
              return console.error(textStatus);
            };
          })(this)
        });
        return;
      }
      this.hideLoading();
      this.scene.traverse((function(_this) {
        return function(object) {
          if (object.material != null) {
            return _this.on3DPlaneMouseOut(object);
          }
        };
      })(this));
      this.clickedObjectWPosition = this.initialObjectsProperties[this.clickedObject.name].position.clone();
      this.clickedObjectWRotation = this.initialObjectsProperties[this.clickedObject.name].quaternion.clone();
      this.clickedObjectWScale = this.initialObjectsProperties[this.clickedObject.name].scale.clone();
      newPos = this.getFocusedPagePosition();
      this.clickedObject.page.css({
        "pointer-events": "none"
      });
      TweenMax.to(this.clickedObject.position, this.TRANSITION_DURATION, {
        x: newPos.x,
        y: newPos.y,
        z: newPos.z,
        onUpdateParams: [this.clickedObject],
        onUpdate: this.syncCss3dPlanePosition,
        onCompleteParams: [this.clickedObject, callback],
        onComplete: (function(_this) {
          return function(object, callback) {
            object.page.css({
              "pointer-events": ""
            });
            _this.doRender = false;
            _this.syncCss3dPlanePosition(object);
            _this.onWindowResize();
            _this.render();
            return typeof callback === "function" ? callback() : void 0;
          };
        })(this)
      });
      camRot = this.camera.quaternion.clone();
      rot2 = new THREE.Quaternion();
      rot2.setFromAxisAngle(new THREE.Vector3(1, 0, 0), Math.PI / 2);
      camRot.multiply(rot2);
      TweenMax.to(this.clickedObject.quaternion, this.TRANSITION_DURATION, {
        x: camRot.x,
        y: camRot.y,
        z: camRot.z,
        w: camRot.w,
        onUpdateParams: [this.clickedObject],
        onUpdate: this.syncCss3dPlaneRotation,
        onCompleteParams: [this.clickedObject],
        onComplete: this.syncCss3dPlaneRotation
      });
      TweenMax.to(this.clickedObject.scale, this.TRANSITION_DURATION, {
        x: 1,
        y: 1,
        z: 1,
        onUpdateParams: [this.clickedObject],
        onUpdate: this.syncCss3dPlaneScale,
        onCompleteParams: [this.clickedObject],
        onComplete: this.syncCss3dPlaneScale
      });
      if (this.isWebGLCapable) {
        TweenMax.to(this.clickedObject.material.uniforms.opacity, this.TRANSITION_DURATION, {
          value: 0
        });
      } else {
        TweenMax.to(this.clickedObject.material, this.TRANSITION_DURATION, {
          opacity: 0
        });
      }
      this.clickedObject.page.css({
        display: "block"
      });
      TweenMax.to(this.clickedObject.page[0], this.TRANSITION_DURATION, {
        css: {
          opacity: 1
        }
      });
      $(".close-page").show();
      return null;
    };

    App.prototype.unfocus = function(callback) {
      this.doRender = true;
      this.isFocused = false;
      this.animate();
      TweenMax.to(this.clickedObject.position, this.TRANSITION_DURATION, {
        x: this.clickedObjectWPosition.x,
        y: this.clickedObjectWPosition.y,
        z: this.clickedObjectWPosition.z,
        onUpdateParams: [this.clickedObject],
        onUpdate: this.syncCss3dPlanePosition,
        onCompleteParams: [this.clickedObject],
        onComplete: this.syncCss3dPlanePosition
      });
      TweenMax.to(this.clickedObject.quaternion, this.TRANSITION_DURATION, {
        x: this.clickedObjectWRotation.x,
        y: this.clickedObjectWRotation.y,
        z: this.clickedObjectWRotation.z,
        w: this.clickedObjectWRotation.w,
        onUpdateParams: [this.clickedObject],
        onUpdate: this.syncCss3dPlaneRotation,
        onCompleteParams: [this.clickedObject],
        onComplete: this.syncCss3dPlaneRotation
      });
      TweenMax.to(this.clickedObject.scale, this.TRANSITION_DURATION, {
        x: this.clickedObjectWScale.x,
        y: this.clickedObjectWScale.y,
        z: this.clickedObjectWScale.z,
        onUpdateParams: [this.clickedObject],
        onUpdate: this.syncCss3dPlaneScale,
        onCompleteParams: [this.clickedObject],
        onComplete: this.syncCss3dPlaneScale
      });
      if (this.isWebGLCapable) {
        TweenMax.to(this.clickedObject.material.uniforms.opacity, this.TRANSITION_DURATION, {
          value: 1
        });
      } else {
        TweenMax.to(this.clickedObject.material, this.TRANSITION_DURATION, {
          opacity: 1
        });
      }
      this.unfocusingTween = TweenMax.to(this.clickedObject.page[0], this.TRANSITION_DURATION, {
        css: {
          opacity: 0
        },
        onCompleteParams: [this.clickedObject, callback],
        onComplete: (function(_this) {
          return function(object, callback) {
            object.page.find("main").remove();
            object.page.css({
              display: "none"
            });
            _this.unfocusingTween = null;
            return typeof callback === "function" ? callback() : void 0;
          };
        })(this)
      });
      $(".close-page").hide();
      return null;
    };

    App.prototype.syncCss3dPlaneScale = function(object) {
      return object.cssObj.scale.set(object.scale.x * this.PAGE_SCALE_MULTIPLIER, object.scale.y * this.PAGE_SCALE_MULTIPLIER, object.scale.z * this.PAGE_SCALE_MULTIPLIER);
    };

    App.prototype.syncCss3dPlanePosition = function(object) {
      return object.cssObj.position.set(object.position.x * this.SCENE_SCALE_MULTIPLIER, object.position.y * this.SCENE_SCALE_MULTIPLIER, object.position.z * this.SCENE_SCALE_MULTIPLIER);
    };

    App.prototype.syncCss3dPlaneRotation = function(object) {
      var rot2;
      object.cssObj.quaternion.set(object.quaternion.x, object.quaternion.y, object.quaternion.z, object.quaternion.w);
      rot2 = new THREE.Quaternion();
      rot2.setFromAxisAngle(new THREE.Vector3(1, 0, 0), -Math.PI / 2);
      return object.cssObj.quaternion.multiply(rot2);
    };

    App.prototype.getFocusedPagePosition = function() {
      var forward, newPos, right, rotMat, xDistance, zDistance;
      rotMat = new THREE.Matrix4();
      rotMat.makeRotationFromQuaternion(this.camera.quaternion);
      forward = new THREE.Vector3(0, 0, -1);
      forward.applyMatrix4(rotMat);
      forward.normalize();
      right = new THREE.Vector3(1, 0, 0);
      right.applyMatrix4(rotMat);
      right.normalize();
      zDistance = window.innerHeight * 0.00065;
      xDistance = 0;
      right.multiplyScalar(xDistance);
      forward.multiplyScalar(zDistance);
      newPos = this.camera.position.clone();
      newPos.x -= this.scene.position.x;
      newPos.y -= this.scene.position.y;
      newPos.z -= this.scene.position.z;
      newPos.x /= this.SCENE_SCALE_MULTIPLIER;
      newPos.y /= this.SCENE_SCALE_MULTIPLIER;
      newPos.z /= this.SCENE_SCALE_MULTIPLIER;
      newPos.add(right);
      newPos.add(forward);
      return newPos;
    };

    App.prototype.onWindowResize = function() {
      var pos, _ref, _ref1;
      this.CONTAINER_X = this.container.position().left;
      this.SCREEN_WIDTH = window.innerWidth - this.CONTAINER_X;
      this.SCREEN_HEIGHT = window.innerHeight;
      this.windowHalfX = this.SCREEN_WIDTH / 2;
      this.windowHalfY = this.SCREEN_HEIGHT / 2;
      this.camera.aspect = this.SCREEN_WIDTH / this.SCREEN_HEIGHT;
      this.camera.updateProjectionMatrix();
      if ((_ref = this.renderer) != null) {
        _ref.setSize(this.SCREEN_WIDTH, this.SCREEN_HEIGHT);
      }
      if ((_ref1 = this.css3dRenderer) != null) {
        _ref1.setSize(this.SCREEN_WIDTH, this.SCREEN_HEIGHT);
      }
      if (this.isFocused) {
        pos = this.getFocusedPagePosition();
        this.clickedObject.position.set(pos.x, pos.y, pos.z);
        this.clickedObject.cssObj.position.set(pos.x * this.SCENE_SCALE_MULTIPLIER, pos.y * this.SCENE_SCALE_MULTIPLIER, pos.z * this.SCENE_SCALE_MULTIPLIER);
      }
      return this.render();
    };

    App.prototype.onMouseMove = function(event) {
      var mx, my, _ref, _ref1, _ref2, _ref3;
      if (!this.isFocused) {
        event.originalEvent.preventDefault();
      }
      mx = event.clientX || ((_ref = event.originalEvent.touches) != null ? (_ref1 = _ref[0]) != null ? _ref1.clientX : void 0 : void 0) || 0;
      my = event.clientY || ((_ref2 = event.originalEvent.touches) != null ? (_ref3 = _ref2[0]) != null ? _ref3.clientY : void 0 : void 0) || 0;
      this.mouseX = (mx - this.CONTAINER_X) - this.windowHalfX;
      this.mouseY = my - this.windowHalfY;
      this.pickMouseX = ((mx - this.CONTAINER_X) / this.SCREEN_WIDTH) * 2 - 1;
      return this.pickMouseY = -(my / this.SCREEN_HEIGHT) * 2 + 1;
    };

    App.prototype.animate = function() {
      this.render();
      if (this.doRender) {
        return requestAnimationFrame(this.animate);
      }
    };

    App.prototype.render = function() {
      var camX, camY, camZ, lim, mrX, mrY, rangeX, rangeY, t, _ref, _ref1;
      if (!this.isFocused) {
        rangeX = this.maxCameraX - this.minCameraX;
        rangeY = this.maxCameraY - this.minCameraY;
        if (this.lockedOnDeviceMotion || this.prevMotionAnalysis.x !== this.motionAnalysis.rotation.x || this.prevMotionAnalysis.y !== this.motionAnalysis.rotation.y || this.prevMotionAnalysis.z !== this.motionAnalysis.rotation.z) {
          this.deviceMotionChangeTimes++;
          if (this.deviceMotionChangeTimes >= 4) {
            this.lockedOnDeviceMotion = true;
          }
          lim = 4;
          mrX = Math.max(Math.min(this.motionAnalysis.rotation.x, lim), -lim);
          mrY = Math.max(Math.min(this.motionAnalysis.rotation.z, lim), -lim);
          camX = (mrX * rangeX) / (lim * 2);
          camY = (mrY * rangeY) / (lim * 2);
        } else {
          t = (-this.mouseX * Math.PI) / this.SCREEN_WIDTH;
          t += Math.PI / 2;
          camX = 400 * Math.cos(t);
          camZ = 400 * Math.sin(t);
          camY = (-this.mouseY * rangeY) / this.SCREEN_HEIGHT;
        }
        this.camera.position.x += (camX - this.camera.position.x) * 0.05;
        this.camera.position.y += (camY - this.camera.position.y) * 0.05;
        this.camera.position.z += (camZ - this.camera.position.z) * 0.05;
        this.camera.lookAt(this.cameraLookAt);
      }
      this.prevMotionAnalysis.x = this.motionAnalysis.rotation.x;
      this.prevMotionAnalysis.y = this.motionAnalysis.rotation.y;
      this.prevMotionAnalysis.z = this.motionAnalysis.rotation.z;
      this.calcPicking();
      if ((_ref = this.renderer) != null) {
        _ref.render(this.scene, this.camera);
      }
      return (_ref1 = this.css3dRenderer) != null ? _ref1.render(this.css3DScene, this.camera) : void 0;
    };

    App.prototype.calcPicking = function() {
      var intersects, vector;
      vector = new THREE.Vector3(this.pickMouseX, this.pickMouseY, 1);
      this.projector.unprojectVector(vector, this.camera);
      this.raycaster.set(this.camera.position, vector.sub(this.camera.position).normalize());
      intersects = this.raycaster.intersectObjects(this.scene.children);
      if (this.doPicking) {
        if (intersects.length > 0) {
          this.handle3DPlaneMouseInteraction(intersects[0].object, "3d");
        } else {
          this.handle3DPlaneMouseInteraction(null, "3d");
          this.overObject = null;
        }
      }
      if ((this.overObject != null) && !this.isFocused) {
        return $("body").css('cursor', 'pointer');
      } else {
        return $("body").css('cursor', '');
      }
    };

    App.prototype.handle3DPlaneMouseInteraction = function(object, initiator) {
      if ((object == null) && (this.overObject != null)) {
        this.on3DPlaneMouseOut(this.overObject);
        return;
      }
      if (this.overObject !== object) {
        if (this.overObject) {
          this.on3DPlaneMouseOut(this.overObject, initiator);
        }
        if (this.excludeFromPicking.indexOf(object.name) === -1) {
          this.overObject = object;
          this.on3DPlaneMouseOver(this.overObject, initiator);
          if (!this.isFocused) {
            return ga('send', 'event', '3d-plane:' + this.overObject.link, 'over');
          }
        } else {
          return this.overObject = null;
        }
      }
    };

    App.prototype.getUpDirs = function(howMany) {
      var i, retValue, _i;
      retValue = "";
      for (i = _i = 0; _i < howMany; i = _i += 1) {
        retValue += "../";
      }
      return retValue;
    };

    App.prototype.getRelativeLink = function(objectPermalink) {
      var updirs;
      updirs = this.getUpDirs(this.pageDepth);
      if (this.pageDepth > 0) {
        return updirs.substr(0, updirs.length - 1) + objectPermalink;
      } else {
        return "." + objectPermalink;
      }
    };

    App.prototype.checkWebGL = function() {
      var isStockAndroid, ua;
      ua = navigator.userAgent.toLowerCase();
      isStockAndroid = /android/.test(ua) && !/chrome/.test(ua);
      try {
        return !!window.WebGLRenderingContext && !!document.createElement('canvas').getContext('experimental-webgl') && !isStockAndroid;
      } catch (_error) {
        return false;
      }
    };

    App.prototype.showLoading = function() {
      $("body").spin({
        lines: 8,
        length: 8,
        width: 5,
        radius: 11,
        corners: 1,
        rotate: 0,
        direction: 1,
        color: '#444',
        speed: 1.3,
        trail: 60,
        shadow: true,
        hwaccel: true,
        className: 'spinner',
        zIndex: 2e9,
        top: '50%',
        left: '50%'
      });
      return null;
    };

    App.prototype.hideLoading = function() {
      $("body").spin(false);
      return null;
    };

    return App;

  })();

  $(document).ready(function() {
    return window.app = new App();
  });

}).call(this);
